[package]
name = "gentoo-build-server"
version = "0.1.0"
authors = ["otakuto <otakuto893@gmail.com>"]

[dependencies]
iron = "0.4"
valico = "1.0.1"
hyper = "0.9"
rustless = "0.10.0"
rust-crypto = "^0.2"
bson = "0.10.0"
mongodb = "0.3.7"
serde_json = "1.0.8"
