#!/bin/bash

GENTOO_BUILD_SERVER=$1
ATOM=$2
PKGDIR='/usr/portage/packages'

emerge -pv ${ATOM} || exit

atoms=(`emerge -pq ${ATOM} | sed -e 's/\[.*\]//g' | tr -d ' '`)

downloads=()

for atom in ${atoms[*]}; do
	echo ${atom}
	rest_url=$(qatom --format '%{CATEGORY}/%{PN}/%{PV}-%[PR]' ${atom} | sed -e 's/-$//')
	uses_json=$(equery -q u ${atom} | sed -e 's/\([+-]\)\(.*\)/"\2":\1/' -e 's/-$/false/' -e 's/+$/true/' -e 's/.*/\0,/')
	uses_json=${uses_json::-1}
	download=$(curl -s -H "Accept: application/json" -H "Content-type: application/json" -X POST -d "{\"use\":{${uses_json}}}" ${GENTOO_BUILD_SERVER}/api/1/atoms/gentoo/${rest_url}/builds)
	echo ${download}
	downloads+=(${download})
done

for (( i = 0; i < ${#downloads[*]}; ++i )); do
	category=$(qatom --format '%{CATEGORY}' ${atoms[i]})
	package=$(qatom --format '%{PN}' ${atoms[i]})
	version=$(qatom -F '%{PV}-%[PR]' ${atoms[i]} | sed -e 's/-$//')

	echo Wait for ${category}/${package}-${version}.tbz2

	while [[ $(curl -s ${GENTOO_BUILD_SERVER}/api/1/atoms/${downloads[i]}/status) != "success" ]]; do
		sleep 10
		echo -n '.'
	done
	mkdir -p ${PKGDIR}/${category}
	if curl -s -o ${PKGDIR}/${category}/${package}-${version}.tbz2 ${GENTOO_BUILD_SERVER}/api/1/atoms/${downloads[i]}; then
		echo OK.
	else
		echo Failed!
	fi
done

emerge -av --usepkg ${ATOM}
